stages:
  - build
  - deploy

variables:
  AWS_REGION: "sa-east-1"  # Região da AWS
  TF_STATE_BUCKET: "app-gp2-s3"  # Nome do bucket do estado do Terraform
  AWS_ACCESS_KEY_ID: "AKIAV4YTWNKPKD6RT6WF"  # Chave de acesso da AWS
  AWS_SECRET_ACCESS_KEY: "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"  # Chave secreta de acesso da AWS

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package
    - mvn test
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - mkdir deployment
    - ls
    - cp target/*.jar deployment/
    - cp appspec.yml deployment/
    - cp scripts/* deployment/
    - cd deployment
    - zip -r my-application.zip .
    - aws s3 cp my-application.zip s3://$TF_STATE_BUCKET/
    - aws deploy create-deployment --application-name g2-odecasa-dev --deployment-group-name back-prod --s3-location bundleType=zip,bucket=$TF_STATE_BUCKET,key=my-application.zip

  only:
    - main
    - dev-back
