stages:
  - build
  - deploy

variables:
  TF_VERSION: "1.5.2"  # Versão do Terraform a ser utilizada
  AWS_REGION: "sa-east-1"  # Região da AWS
  TF_STATE_BUCKET: "app-gp2-s3"  # Nome do bucket do estado do Terraform
  AWS_ACCESS_KEY_ID: "AKIAV4YTWNKPKD6RT6WF"  # Chave de acesso da AWS
  AWS_SECRET_ACCESS_KEY: "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"  # Chave secreta de acesso da AWS

before_script:
  - apt add --update openssl openssh-client unzip
  - wget "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
  - rm -rf terraform  # Remover o diretório "terraform" se existir
  - unzip -o "terraform_${TF_VERSION}_linux_amd64.zip"
  - mv terraform /usr/bin/
  - rm "terraform_${TF_VERSION}_linux_amd64.zip"
  - terraform --version

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package
    - mvn test
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: hashicorp/terraform:${TF_VERSION}
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=terraform.tfstate" -backend-config="region=${AWS_REGION}"
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  only:
    - main
