stages:
  - build
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - aws configure set aws_access_key_id AKIAV4YTWNKPKD6RT6WF
    - aws configure set aws_secret_access_key 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
    - aws configure set region sa-east-1
    - aws s3 cp s3://bucket-gp2/demo-0.0.1-SNAPSHOT.jar ./demo-0.0.1-SNAPSHOT.jar
    - docker pull tomcat:9-jdk11-openjdk-slim
    - docker run -d -p 8080:8080 --name tomcat_container tomcat:9-jdk11-openjdk-slim
    - docker cp ./demo-0.0.1-SNAPSHOT.jar tomcat_container:/usr/local/tomcat/webapps/
    - docker exec tomcat_container catalina.sh run
