stages:
  - build
  - deploy

variables:
  AWS_REGION: "sa-east-1"  # Região da AWS
  TF_STATE_BUCKET: "app-gp2-s3"  # Nome do bucket do estado do Terraform
  AWS_ACCESS_KEY_ID: "AKIAV4YTWNKPKD6RT6WF"  # Chave de acesso da AWS
  AWS_SECRET_ACCESS_KEY: "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"  # Chave secreta de acesso da AWS

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package
    - mvn test
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_REGION=$AWS_REGION
    - mkdir deployment
    - ls
    - cp target/*.jar deployment/
    - cp appspec.yml deployment/
    - cp stop-application.sh deployment/
    - cp install-dependencies.sh deployment/
    - cp start-application.sh deployment/    
    - cd deployment
    - yum install -y zip unzip
    - zip -r my-application.zip .
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - aws s3 cp my-application.zip s3://$TF_STATE_BUCKET/
    - aws deploy create-deployment --region sa-east-1 --application-name g2-odecasa-dev --deployment-group-name back-prod --s3-location bucket=$TF_STATE_BUCKET,key=my-application.zip,bundleType=zip

  only:
    - main
    - dev-back
