stages:
  - build
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.war

deploy:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws configure set aws_access_key_id <AKIAV4YTWNKPH6TELH3W>
    - aws configure set aws_secret_access_key <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>
    - aws configure set region <sa-east-1>
    - aws deploy create-deployment --application-name odecasa-dev --deployment-group-name dev-odecasa --s3-location bucket=<bucket-gp2>,bundleType=zip
