version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: stop-application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start-application.sh
      timeout: 300
      runas: root
